Task#01
apilatau/pythonSandBox pull request #1
Opened 2021-09-13 05:28 UTC by apilatau

2021-09-14 07:22 UTC, 0leksiiLeshchenko requested changes
С алгоритмом все путем, результат есть, нужно поправить стиль кода и нейминг
Если установишь себе Pycharm Community, он покажет тебе подсказки, что поправить https://i.imgur.com/o0JtdZx.png

2021-09-14 07:22 UTC, 0leksiiLeshchenko commented on Task01/NarcissisticNumbers.py
> +sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
А для чего Вы меняете sys.path?
Код работает и без этого

2021-09-14 07:22 UTC, 0leksiiLeshchenko commented on Task01/NarcissisticNumbers.py
> +    print_NarcissisticNumbers(1,1000)
```suggestion
    print_NarcissisticNumbers(1, 1001)
```

range(n, m) - начало диапазона n, а конец m-1 -- (n, m]

2021-09-14 07:22 UTC, 0leksiiLeshchenko commented on Task01/NarcissisticNumbers.py
> +def print_NarcissisticNumbers(minNumber,maxNumber):
Между функциями в Python обычно делают разрыв в 2 строки
Так же, название функции лучше изменить что бы оно было в каком-то одном стиле, то есть - слова с маленькой буквы разделенные _ (print_narcissistic_numbers), или первое слово с маленькой буквы, а следующие с большой (printNarcissisticNumbers). По [стандарту PEP8](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names), первый способ нейминга считаеться более предпочтительным.
Там же можно почитать и про нейминг переменных, аргументов и т д.
Если поставишь Pycharm, он будет тебе все это подсказывать https://i.imgur.com/2PfCT9N.png

2021-09-14 07:22 UTC, 0leksiiLeshchenko commented on Task01/NarcissisticNumbers.py
> +    input_list = list(range(minNumber,maxNumber,1))
```suggestion
    input_list = list(range(minNumber, maxNumber))
```
Единичка для параметра step функции range указана по умолчанию

2021-09-14 07:22 UTC, 0leksiiLeshchenko commented on Task01/NarcissisticNumbers.py
> +            print(input_Item, end =" ")
```suggestion
            print(input_Item, end=" ")
```
keyword parameters указывают без пробелов

2021-09-14 12:29 UTC, 0leksiiLeshchenko requested changes

2021-09-14 12:29 UTC, 0leksiiLeshchenko commented on Task01/NarcissisticNumbers.py
> +if __name__=="__main__":
А для чего вы запукаете код через if __name__=="__main__"?

2021-09-15 10:31 UTC, apilatau commented on Task01/NarcissisticNumbers.py
> +if __name__=="__main__":
я на каком то стек оверфлоу наз прочитал, что типа бест практис вызывать код через какую то общую точку / функцию например все через main - например тут : в конце страницы : https://metanit.com/python/tutorial/2.8.php

2021-09-15 12:20 UTC, 0leksiiLeshchenko commented on Task01/NarcissisticNumbers.py
> +if __name__=="__main__":
Да, верно, но использовать `if __name__=="__main__":` имеет смысл когда у тебя есть import чего-то. 
При import файл в Python исполняется, что бы не было побочных эффектов от исполнения импортируемых файлов, используют эту констукцию. В данном случае она не нужна

2021-09-15 12:47 UTC, 0leksiiLeshchenko requested changes

2021-09-15 12:47 UTC, 0leksiiLeshchenko commented on Task01/NarcissisticNumbers.py
> +
не используем, можно удалить

2021-09-15 12:47 UTC, 0leksiiLeshchenko commented on Task01/NarcissisticNumbers.py
> +def print_narcissistic_numbers(minNumber,maxNumber):
```suggestion
def print_narcissistic_numbers(minNumber, maxNumber + 1):
```

2021-09-15 12:47 UTC, 0leksiiLeshchenko commented on Task01/NarcissisticNumbers.py
> +    input_list = list(range(minNumber,maxNumber))
```suggestion
    input_list = list(range(minNumber, maxNumber))
```

2021-09-15 12:47 UTC, 0leksiiLeshchenko commented on Task01/NarcissisticNumbers.py
> +        i+=1
```suggestion
        i += 1
```

2021-09-15 12:47 UTC, 0leksiiLeshchenko commented on Task01/NarcissisticNumbers.py
> +if __name__=="__main__":
```suggestion
if __name__ == "__main__":
```

2021-09-15 12:47 UTC, 0leksiiLeshchenko commented on Task01/NarcissisticNumbers.py
> +    print_narcissistic_numbers(1,1001)
```suggestion
    print_narcissistic_numbers(1, 1000)
```
тут я дал маху. Мы в функцию должны передавать числа в диапазоне которых мы ищем narcissistic numbers, а уже когда используем их в range - тогда и добавляем единичку, так как последнее число не включаеться в диапазон. поправлять нужно не тут, а в range

2021-09-15 12:47 UTC, 0leksiiLeshchenko commented on Task01/NarcissisticNumbers.py
> +if __name__=="__main__":
Я бы удалил `if __name__=="__main__":` и просто ранил main()

2021-09-15 13:20 UTC, apilatau commented on Task01/NarcissisticNumbers.py
> +if __name__=="__main__":
агри счас удалю

2021-09-15 14:03 UTC, apilatau commented on Task01/NarcissisticNumbers.py
> +def print_narcissistic_numbers(minNumber,maxNumber):
это на сколько я понимаю синтаксически не проходит - это не дот нет :) он ожидает скобочку )

2021-09-15 14:10 UTC, apilatau commented on Task01/NarcissisticNumbers.py
> +if __name__=="__main__":
я в конце этот иф удали, а написал просто main() потому что без этой строчки действительно не работает

2021-09-15 14:10 UTC, apilatau commented on Task01/NarcissisticNumbers.py
> +    print_narcissistic_numbers(1,1001)
в рандже я поправил, смотри

2021-09-15 15:57 UTC, 0leksiiLeshchenko requested changes
Это последние :)

2021-09-15 15:57 UTC, 0leksiiLeshchenko commented on Task01/NarcissisticNumbers.py
> +
```suggestion
```

2021-09-15 15:57 UTC, 0leksiiLeshchenko commented on Task01/NarcissisticNumbers.py
> +    print_narcissistic_numbers(1,1000)
```suggestion
    print_narcissistic_numbers(1, 1000)
```

2021-09-15 15:57 UTC, 0leksiiLeshchenko commented on Task01/NarcissisticNumbers.py
> +def main():
По сути `main()` тут и не нужна ведь она ранит всего 1 функцию. просто запускай `print_narcissistic_numbers` и все.

2021-09-16 07:23 UTC, 0leksiiLeshchenko approved these changes

2021-09-16 10:35 UTC, merged