Task03
apilatau/pythonSandBox pull request #3
Opened 2021-09-20 08:27 UTC by apilatau

2021-09-28 22:05 UTC, 0leksiiLeshchenko requested changes

2021-09-28 22:05 UTC, 0leksiiLeshchenko commented on Task03/FindWordOccurence.py
> +            index_sentence = sentence_words.index(word)
А зачем ты берешь индекс слова?

2021-09-28 22:05 UTC, 0leksiiLeshchenko commented on Task03/FindWordOccurence.py
> +            continue
Строить логику на ошибке программы не верно

2021-09-28 22:05 UTC, 0leksiiLeshchenko commented on Task03/FindWordOccurence.py
> +            print(word.ljust(7), words_dict[word], index_occerence)
Используй f-strings для форматирования вывода

2021-09-28 22:05 UTC, 0leksiiLeshchenko commented on Task03/FindWordOccurence.py
> +        print("word    count")
word    count   first line

2021-10-01 09:59 UTC, apilatau commented on Task03/FindWordOccurence.py
> +            index_sentence = sentence_words.index(word)
здесь констатируется факт или не факт нахождения слова, как входящего параметра функции get_index_text в рассплитанном по словам предложении

2021-10-01 10:01 UTC, apilatau commented on Task03/FindWordOccurence.py
> +            continue
считаю это оправданным в виду того, что осуществляется поиск входящего слова в разделенном по словам предложении в виду особенностей работы функции index- т.е. находится индекс входящего элемента, если нет, то выбрасывается экспешен самой функций

2021-10-01 10:59 UTC, apilatau commented on Task03/FindWordOccurence.py
> +            print(word.ljust(7), words_dict[word], index_occerence)
я ее использовал, но без ljust из-за переменной длины слова остальные колонок разный старт

2021-10-05 23:05 UTC, 0leksiiLeshchenko approved these changes

2021-10-05 23:05 UTC, 0leksiiLeshchenko commented on Task03/FindWordOccurence.py
> +            print(f"{word.ljust(7)}         {words_dict[word]}       {index_occerence}")
```suggestion
        print(f"{'word':10}{'count':<10}{'occurrence':>10}")
        for word in words_dict:
            index_occerence = get_index_text(word)
            print(f"{word:<10}{words_dict[word]:<10}{index_occerence:<10}")
```

Так все же красивее

2021-10-05 23:05 UTC, 0leksiiLeshchenko commented on Task03/FindWordOccurence.py
> +def get_index_text(word):
```suggestion

def get_index_text(word):
```

2021-10-05 23:50 UTC, merged