task04
apilatau/pythonSandBox pull request #4
Opened 2021-09-27 00:45 UTC by apilatau

2021-09-28 22:22 UTC, 0leksiiLeshchenko requested changes

2021-09-28 22:22 UTC, 0leksiiLeshchenko commented on Task04/recursion.py
> +
```suggestion
```

2021-09-28 22:22 UTC, 0leksiiLeshchenko commented on Task04/recursion.py
> +    return list_result
Логику программы нельзя строить на exceptions

2021-09-28 22:22 UTC, 0leksiiLeshchenko commented on Task04/recursion.py
> +           key = get_key_by_index(item, 0)
Зачем мы берем `key`, если потом нигде его не используем?

2021-10-01 11:12 UTC, apilatau commented on Task04/recursion.py
> +           key = get_key_by_index(item, 0)
а вот это хороший вопрос, тут согласен

2021-10-01 11:26 UTC, apilatau commented on Task04/recursion.py
> +    return list_result
не всегда но можно! :) суть здесь в том, что для того чтобы перебрать value у дикшинари другим способом как через этот for вытянуть это значение, как я понимаю нельзя ( т.е взять конретный айтем из получаемой структры values dictionary) . При этом по условию мы используем одну рекурсивную функцию , в которой передаем только один параметр - этот дикшинари. Идея алгоритма в том, чтобы "понизить" уровень иерархии дерева, т.е. сделать его плоским из любого уровня "иерархических" разветвлений, либо изменить условие задачи и передавать в сигнатуре что то еще. А эксепшен выкидывается естественно, потому что в соответствии с этим мы при каждом заходе вынуждены менять этот дикшинари. Другое дело, что может в питоне есть какая то проверка как в дотнете например, ты можешь в каком то своем case выкинуть свой конкретный эксепшен, если выкинится другой, значит ошибка - нельзя так! а если свой то обработать как обычный if

2021-10-01 11:28 UTC, apilatau commented on Task04/recursion.py
> +
fixed

2021-10-05 23:08 UTC, 0leksiiLeshchenko approved these changes

2021-10-05 23:08 UTC, 0leksiiLeshchenko commented on Task04/recursion.py
> +    if isinstance(items,dict):
```suggestion
    if isinstance(items, dict):
```

2021-10-05 23:08 UTC, 0leksiiLeshchenko commented on Task04/recursion.py
> +assert recursion(tree) == expected_result_tree,"incorrect tree plot"
```suggestion
assert recursion(tree) == expected_result_tree, "incorrect tree plot"
```

2021-10-05 23:08 UTC, 0leksiiLeshchenko commented on Task04/recursion.py
> +assert recursion(flat_tree) == flat_tree,"incorrect tree plot"
```suggestion
assert recursion(flat_tree) == flat_tree, "incorrect tree plot"

```

2021-10-06 00:01 UTC, merged