task05
apilatau/pythonSandBox pull request #5
Opened 2021-09-27 02:30 UTC by apilatau

2021-09-28 22:33 UTC, 0leksiiLeshchenko requested changes
Решение правильное, но слегка избыточное. 
Советую перед решением посмотреть видео https://www.youtube.com/watch?v=Zb3lF4qfElA&list=PLlWXhlUMyooaeSj8L8tVVbtUo0WCO4ORR&index=7 и прочитать статью https://realpython.com/python-kwargs-and-args/
Задание решается в 2 строки, но вначале нужно изучить инфу по параметрам функций в Python

2021-10-01 11:50 UTC, apilatau commented
> Решение правильное, но слегка избыточное. Советую перед решением посмотреть видео https://www.youtube.com/watch?v=Zb3lF4qfElA&list=PLlWXhlUMyooaeSj8L8tVVbtUo0WCO4ORR&index=7 и прочитать статью https://realpython.com/python-kwargs-and-args/ Задание решается в 2 строки, но вначале нужно изучить инфу по параметрам функций в Python

2021-10-05 23:13 UTC, 0leksiiLeshchenko approved these changes
Если бы ты поставил Pycharm он бы подсказал бы тебе как правильно перенести строки

2021-10-05 23:13 UTC, 0leksiiLeshchenko commented on Task05/args_kwargs.py
> +print(create_user("John", "Doe"))
```suggestion

print(create_user("John", "Doe"))
```

2021-10-05 23:13 UTC, 0leksiiLeshchenko commented on Task05/args_kwargs.py
> +assert create_user("John", "Doe") == {'name': 'John', 'surname': 'Doe', 'age': 42, 'extra':{}}, "invalid dictionary build"
```suggestion
assert create_user("John", "Doe") == \
       {'name': 'John', 'surname': 'Doe', 'age': 42, 'extra': {}}, "invalid dictionary build"
```

2021-10-05 23:13 UTC, 0leksiiLeshchenko commented on Task05/args_kwargs.py
> +assert create_user("Bill", "Gates", age=65) == {'name': 'Bill', 'surname': 'Gates', 'age': 65, 'extra':{}}, "invalid dictionary build"
```suggestion
assert create_user("Bill", "Gates", age=65) == \
       {'name': 'Bill', 'surname': 'Gates', 'age': 65, 'extra': {}}, "invalid dictionary build"
```

2021-10-05 23:13 UTC, 0leksiiLeshchenko commented on Task05/args_kwargs.py
> +assert create_user("Marie", "Curie", age=66, occupation="physicist", won_nobel=True) == {'name': 'Marie', 'surname': 'Curie', 'age': 66, 'extra': {'occupation': 'physicist', 'won_nobel': True}},"inva
```suggestion
assert create_user("Marie", "Curie", age=66, occupation="physicist", won_nobel=True) == {
    'name': 'Marie', 'surname': 'Curie', 'age': 66, 'extra': {'occupation': 'physicist', 'won_nobel': True}},\
    "invalid dictionary build"```

2021-10-06 00:08 UTC, merged